name: test_2
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/clothing.jpg
    - assets/images/beauty.jpg
    - assets/images/electronic.jpg
    - assets/images/furniture.jpg
    - assets/images/jewlery.jpg
    - assets/images/mobile.jpg
    - assets/images/shoes.jpg
    - assets/images/toys.jpg
    - assets/imgaes/fashion.jpg   